quarkus.application.name=${OTEL_SERVICE_NAME:oficina-auth-sync-lambda}
quarkus.lambda.handler=usuario-sync
quarkus.datasource.db-kind=postgresql

quarkus.log.console.json.enabled=${OFICINA_OBSERVABILITY_JSON_LOGS_ENABLED:true}
quarkus.log.console.json.exception-output-type=detailed
quarkus.log.console.json.additional-field."service.name".value=${quarkus.application.name}
quarkus.log.console.json.additional-field."service.namespace".value=oficina
quarkus.log.console.json.additional-field."service.version".value=${quarkus.application.version:unknown}
quarkus.log.console.json.additional-field."deployment.environment".value=${DEPLOYMENT_ENVIRONMENT:lab}

%prod.quarkus.datasource.jdbc.initial-size=0
%prod.quarkus.datasource.jdbc.min-size=0
%prod.quarkus.datasource.jdbc.max-size=2
%prod.quarkus.datasource.jdbc.acquisition-timeout=5S

%dev.quarkus.datasource.username=app
%dev.quarkus.datasource.password=app
%dev.quarkus.datasource.devservices.port=36759
%dev.quarkus.datasource.devservices.db-name=app
%dev.quarkus.log.console.json.enabled=false

%test.quarkus.datasource.db-kind=postgresql
%test.quarkus.datasource.devservices.enabled=false
%test.quarkus.secretsmanager.devservices.enabled=false
%test.quarkus.log.console.json.enabled=false
