quarkus.application.name=oficina-auth-sync-lambda
quarkus.lambda.handler=authSync
quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.jdbc.initial-size=0
%prod.quarkus.datasource.jdbc.min-size=0
%prod.quarkus.datasource.jdbc.max-size=2
%prod.quarkus.datasource.jdbc.acquisition-timeout=5S

%test.quarkus.datasource.devservices.enabled=true
%test.quarkus.datasource.devservices.image-name=postgres:16-alpine
%test.quarkus.datasource.devservices.init-script-path=init.sql
%test.quarkus.lambda.mock-event-server.test-port=9082
