%dev.quarkus.lambda.mock-event-server.dev-port=9082
%dev.quarkus.swagger-ui.always-include=true
%dev.quarkus.mailer.from=noreply@oficina.local
%dev.quarkus.mailer.mock=true

%test.quarkus.lambda.mock-event-server.test-port=9083
%test.quarkus.mailer.from=noreply@oficina.test
%test.quarkus.mailer.mock=true
